apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: globalrolebindings.custom.authorization.global.io
spec:
  group: custom.authorization.global.io
  names:
    kind: GLobalRoleBinding
    plural: globalrolebindings
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        namespaces:
          type: string
        roleRef:
          properties:
            apiGroup:
              type: string
            kind:
              type: string
            name:
              type: string
          required:
          - apiGroup
          - kind
          - name
          type: object
        subjects:
          items:
            properties:
              apiGroup:
                type: string
              kind:
                type: string
              name:
                type: string
            required:
            - kind
            - apiGroup
            - name
            type: object
          type: array
      required:
      - subjects
      - roleRef
      - namespaces
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
