apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - v1
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - rbac
  resources:
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - custom.authorization.global.io
  resources:
  - globalrolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
