apiVersion: custom.authorization.global.io/v1alpha1
kind: GlobalRoleBinding
metadata:
  name: globalrolebinding-engineers
spec:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: engineers
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: engineers
namespaces: "nu-*"
