apiVersion: custom.authorization.global.io/v1alpha1
kind: GLobalRoleBinding
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: globalrolebinding-sample
spec:
  # Add fields here
  foo: bar
